# Creates Replicaset 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 10
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
     app: nginx
  ports:
    - protocol: TCP
      port: 80                         # Port number that your service has to listen and this is the port you will access
      targetPort: 80                   # TargetPort forwards the requests to the backend pod